### ISSUE TITLE
Wie kann hier der Timetable angezeigt werden?

### ISSUE THREAD

**Issue by davidblumer** [ToolboxBodensee/tdott19-info-beamer#1]
Wie kann hier der Timetable angezeigt werden? @DO1JLR

**Comment by DO1JLR** [comment]
Der info-beamer (nicht teil dieses git repos sondern erhaältlich bei https://info-beamer.com/ ) unterstützt unter anderen JSON und ähnliche Datenformate.

Daher kann man mit ``make -B -C pfad_ins_repo all`` den fahrplan downloaden, in die richtige syntax umschreiben und vom info-beamer darstellen lassen!

**Comment by DO1JLR** [comment]
https://github.com/ToolboxBodensee/tdott19-info-beamer/blob/master/fetch#L7
Dort steht die Fahrplan URL zum Beispiel!
